name: LLM Code Reviewer

on:
  pull_request:
    branches: [master]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get Modified files
        id: files
        uses: actions/github-script@v6
        with:
          script: |
            const files = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            const modifiedFiles = files.data.map(f => f.filename)
                  .filter(f => f.endsWith('.cs') || f.endsWith('.js') || f.endsWith('.py'));
            core.setOutput("modfiedFiles", modfiedFiles.join(" "));
            result-encoding: string

      - name: Python-setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dependencies.txt


      - name: Run code Reviewer
        run: |
          python scripts/pr-reviewer.py "${{ steps.files.outputs.modfiedFiles }}"
        env:
          OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
          PR_USERNAME: ${{ github.event.pull_request.user.login }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}