name: LLM Code Reviewer

on:
  pull_request_target:
    branches: [master]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get Modified files
        id: files
        run: |
          MODIFIED_FILES=$(gh pr view "${{ github.event.pull_request.number }}" --json files --jq '.files[].path' | grep -E '\.cs$|\.js$|\.py$' | tr '\n' ' ')
          echo "modifiedFiles=$MODIFIED_FILES" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Python-setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai requests


      - name: Run code Reviewer
        run: |
          python scripts/pr-reviewer.py "${{ steps.files.outputs.modifiedFiles }}"
        env:
          OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
          PR_USERNAME: ${{ github.event.pull_request.user.login }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
